/**:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mobile_base_controller_rubber:
      type: romea_mobile_base_controllers/MobileBaseController4WD

    mobile_base_controller_mecanum:
      type: romea_mobile_base_controllers/MobileBaseController4MWD
