# kinematic: omni_steering
type: 4WMD
geometry:
  axles_distance: 0.52
  front_axle:
    wheels_distance: 0.685
    wheels:
      radius: 0.2032
      width: 0.1651
      hub_carrier_offset: 0.0
  rear_axle:
    wheels_distance: 0.685
    wheels:
      radius: 0.2032
      width: 0.1651
      hub_carrier_offset: 0.0
  aabb:
    length: 2.349
    width: 0.7
    height: 1.133
    center: [0.0, 0.0, 1.2]
  ground_clearance: 0.15

wheels_speed_control:
  command:
    maximal_speed: 3.0
    maximal_acceleration: 1.0
  sensor:
    speed_std: 0.1
    speed_range: 3.0

inertia:
  mass: 174.0
  center: [0.0, 0.0, 0.71650]
  z_moment: 0.0

control_point : [0.0, 0.0, 0.0]

joints:
base_footprint_joint_name: base_footprint_joint
inertial_joint_name: initial_joint
front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

links:
  base_link_name: base_link
  base_footprint_link_name: base_footprint
  inertial_link_name: initial_link
  front_left_wheel_steering_link_name: front_left_wheel_steering_link
  front_right_wheel_steering_link_name: front_right_wheel_steering_link
  front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
  front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
  rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
  rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link
