<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:macro name="chassis_visual">
        <visual>
            <!--            <origin xyz="${aabb_center_x-body_reference_x} ${aabb_center_y}
            ${aabb_center_z-chassis_height}" rpy="0 0 0" />-->
            <geometry>
                <mesh filename="package://campero_description/meshes/chassis.stl" />
            </geometry>
        </visual>

    </xacro:macro>


</robot>